# Generated by Django 3.1.1 on 2020-10-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201014_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
