# Generated by Django 3.1.3 on 2020-12-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20201203_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ads.book'),
        ),
    ]
