# Generated by Django 3.1.3 on 2020-12-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20201203_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adtype'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.condition'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.pricetype'),
        ),
    ]
