# Generated by Django 3.1.3 on 2020-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20201209_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='condition',
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ads.condition'),
            preserve_default=False,
        ),
    ]
